name: enpass
base: core18
version: '6.6.0.775'
summary: Offline Password Manager and Secure Vault.
description: |
  Use Enpass to securely organize everything at one place. 

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  enpass:
    command: opt/enpass/Enpass
    desktop: usr/share/applications/enpass.desktop
    extensions: [gnome-3-34]
    plugs:
      - home
      - audio-playback
      - network
      - unity7
      - network-bind

architectures:
  - build-on: amd64
    run-on: amd64

parts:
  enpass-deb:
    plugin: dump
    source: "https://apt.enpass.io/pool/main/e/enpass/enpass_$SNAPCRAFT_PROJECT_VERSION_amd64.deb"
    source-type: deb
    stage-packages:
      - libxss1
      - libxkbcommon-x11-0
    override-prime: |
      snapcraftctl prime
      sed -i 's|Icon=.*|Icon=${SNAP}/meta/gui/enpass.svg|g' $SNAPCRAFT_PRIME/usr/share/applications/enpass.desktop
  snap-gui-folder:
    plugin: dump
    source: icons/
    organize:
      enpass.svg: meta/gui/
